version: ~> 1.0
language: c++
jobs:
  include:
    - name: Linux (Ubuntu Bionic)
      os: linux
      env: TRAVISBUILD=LinuxBionic
      dist: bionic
      # virt: lxd
    - name: Linux (Ubuntu Xenial)
      os: linux
      dist: xenial
      # virt: lxd
      env: 
        - EXTRA_CXXFLAGS="-DARIA_OMIT_DEPRECATED_MATH_FUNCS" 
        - TRAVISBUILD=LinuxXenial
    - name: MacOSX
      os: osx
      env: TRAVISBUILD=MacOSX
#    - name: Linux (Ubuntu Bionic on arm64)
#      os: linux
#      virt: lxd
#      arch: arm64
#      dist: bionic
    - name: Windows (Windows Server 2019 with Visual C++)
      os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
        - TRAVISBUILD=WindowsMSVC
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      script:
#        - ver
        - echo $0
        - echo $PWD
        - echo $VisualStudioVersion
        - cd visualc
        - export PATH=$MSBUILD_PATH:$PATH
        - MSBuild.exe AriaCoda.sln -verbosity:detailed -p:Configuration=Debug -p:Platform=x64 -maxCpuCount
git:
  depth: 1
script:
  - make -s -j4 CXXDEBUGFLAGS= CXXOPTFLAGS=-O0
